version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: FiscalRoiCalculator.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  client:
    build:
      context: ./fiscal-roi-calculator-client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api 